---

- name: Create a directory if it does not exist
  file:
    path: "{{ project_path }}/{{ git_hash }}"
    state: directory
    mode: '0755'
  tags:
    - copy_files

- name: Copy tarball of app to remote
  copy:
    src: "app.tar.gz"
    dest: "{{ project_path }}/{{ git_hash }}/app.tar.gz"
    mode: '0744'
  tags:
    - copy_files

- name: Extract the tarball
  command:
    cmd: "tar -xzf  {{ project_path }}/{{ git_hash }}/app.tar.gz {{ project_path }}/{{ git_hash }} && rm -rf {{ project_path }}/{{ git_hash }}/app.tar.gz"
  tags:
    - copy_files
