addons:
  ssh_known_hosts: ${SSH_HOST}

before_deploy:
  - 'if [ -z ${DEPLOY_SSH_KEY_BASE64} ]; then
        echo ${DEPLOY_SSH_KEY_BASE64} | base64 --decode > /tmp/deploy_rsa
        chmod 600 /tmp/deploy_rsa
        ssh-add /tmp/deploy_rsa
     else
        echo "Error: DEPLOY_SSH_KEY_BASE64 variable is not set!"
     fi'

deploy:
  provider: script
  skip_cleanup: true
  script:
    - curdate=(`date +%Y-%m-%d_%H-%M`)
    - mkdir -p /mnt/disks/weirdstreet/node/${curdate}
    - echo "Directory /mnt/disks/weirdstreet/node/${curdate} has been created"
#    - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR ${SSH_USER}@${SSH_HOST}:/mnt/disks/weirdstreet/node/${curdate}
#    - ln.....
  on:
    branch: cicd
message: "The Wierd Street has been deployed"
