os: linux
dist: bionic
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
#  - sudo apt-get install -qq python-apt

install:
  - echo "================ install Ansible"
#  - pip install ansible==1.9.1
  - sudo apt-get install -qq -y ansible
  - ansible --version

before_script:
  - echo "=============== before script"
  - echo $DEPLOY_SSH_KEY_BASE64
  - echo "${SSH_HOST} ansible_user=${SSH_USER}" > .travisci/inventory
  - cat .travisci/inventory
  - |
    if [ -z ${DEPLOY_SSH_KEY_BASE64+x} ]; then
        echo "Error: DEPLOY_SSH_KEY_BASE64 variable is not set!"
    else
        echo ${DEPLOY_SSH_KEY_BASE64} | base64 --decode > /tmp/deploy_rsa
        chmod 600 /tmp/deploy_rsa
        eval `ssh-agent -s`
        ssh-add /tmp/deploy_rsa
    fi

script:
      - echo "==================Script run"
      - echo ${DEPLOY_SSH_KEY_BASE64}
      - export GIT_HASH=$(git rev-parse --short HEAD)
      - echo "GIT_HASH=${GIT_HASH}"
      - ansible-playbook -i ${SSH_HOST} -e git_hash=${GIT_HASH} .travisci/deploy.yml --syntax-check
after_success:
    - echo "==========End after success script"

branches:
  only:
    - alpha
    - cicd

addons:
  ssh_known_hosts: ${SSH_HOST}

#  script:
#    - curdate=(`date +%Y-%m-%d_%H-%M`)
#    - echo "Start before deploy script: $curdate"
#    - cat /tmp/deploy_rsa
#    - mkdir -p /mnt/disks/weirdstreet/node/${curdate}
#    - echo "Directory /mnt/disks/weirdstreet/node/${curdate} has been created"
#    - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR ${SSH_USER}@${SSH_HOST}:/mnt/disks/weirdstreet/node/${curdate}
#    - ln.....

#jobs:
#  fast_finish: true
#  include:
#    - name: "Create a new deploy folder"
#      node_js: 12
#      stage: Build
#      before_install:
#        - echo "==========Start before deploy script"
#        - echo $DEPLOY_SSH_KEY_BASE64
#        - |
#          if [ -z ${DEPLOY_SSH_KEY_BASE64+x} ]; then
#              echo "Error: DEPLOY_SSH_KEY_BASE64 variable is not set!"
#           else
#              echo ${DEPLOY_SSH_KEY_BASE64} | base64 --decode > /tmp/deploy_rsa
#              chmod 600 /tmp/deploy_rsa
#              ssh-add /tmp/deploy_rsa
#           fi

#      install:
#        - echo "================ install script"
      #      - apt-get install mc
#      before_script:
#        - echo "=============== before script"
      #        - apt-get update
#      script:
#        - echo "==================Script run"
#        - echo ${DEPLOY_SSH_KEY_BASE64}
#      after_success:
#        - echo "==========End after success script"

