os: linux
dist: bionic
language: node_js
node_js:
  - 12
branches:
  only:
    - alpha
    - cicd

#before_script:
#  - yarn install
#  - node shared/install-dependencies.js
#script:
#  - yarn run build:web

addons:
  ssh_known_hosts: ${SSH_HOST}

jobs:
  fast_finish: true
  include:
    - name: "Create a new deploy folder"
      node_js: 12
      stage: Build
      before_install:
        - echo "==========Start before deploy script"
        - 'if [ -z ${DEPLOY_SSH_KEY_BASE64} ]; then
              echo ${DEPLOY_SSH_KEY_BASE64} | base64 --decode > /tmp/deploy_rsa
              chmod 600 /tmp/deploy_rsa
              ssh-add /tmp/deploy_rsa
              echo "Output:"
              cat /tmp/deploy_rsa
           else
              echo "Error: DEPLOY_SSH_KEY_BASE64 variable is not set!"
           fi'
      install:
        - echo "================ install script"
        - apt-get install mc
      before_script:
        - echo "=============== before script"
        - apt-get update
      script:
        - echo "==================Script run"
      after_success:
        - echo "==========End after success script"


#  script:
#    - curdate=(`date +%Y-%m-%d_%H-%M`)
#    - echo "Start before deploy script: $curdate"
#    - cat /tmp/deploy_rsa
#    - mkdir -p /mnt/disks/weirdstreet/node/${curdate}
#    - echo "Directory /mnt/disks/weirdstreet/node/${curdate} has been created"
#    - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR ${SSH_USER}@${SSH_HOST}:/mnt/disks/weirdstreet/node/${curdate}
#    - ln.....

