os: linux
dist: bionic
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
#  - sudo apt-get install -qq python-apt

install:
  - echo "================ install Ansible"
#  - pip install ansible==1.9.1
  - sudo apt-get install -qq -y ansible
  - ansible --version

before_script:
  - echo "=============== before script"
  - echo $DEPLOY_SSH_KEY_BASE64
  - echo "[weirdstreet]" > .travisci/inventory
  - echo "${SSH_HOST} ansible_user=${SSH_USER}" >> .travisci/inventory
  - cat .travisci/inventory
  - |
    if [ -z ${DEPLOY_SSH_KEY_BASE64+x} ]; then
        echo "Error: DEPLOY_SSH_KEY_BASE64 variable is not set!"
    else
        echo ${DEPLOY_SSH_KEY_BASE64} | base64 --decode > /tmp/deploy_rsa
        chmod 600 /tmp/deploy_rsa
        # eval `ssh-agent -s`
        # ssh-add /tmp/deploy_rsa
    fi

script:
      - echo "==================Script run"
      - echo ${DEPLOY_SSH_KEY_BASE64}
      - export GIT_HASH=$(git rev-parse --short HEAD)
      - export PREVIOUS_GIT_HASH=$(git rev-parse --short HEAD^1)
      - echo "GIT_HASH=${GIT_HASH}"
      - echo "PREVIOUS_GIT_HASH=${PREVIOUS_GIT_HASH}"
      - git archive --format=tar ${GIT_HASH} > .travisci/roles/copy_files/files/${GIT_HASH}.tar
      - sudo sed -i 's/#host_key_checking = False/host_key_checking = False/g' /etc/ansible/ansible.cfg
      - ansible-playbook -i .travisci/inventory -e git_hash=${GIT_HASH} -e previous_git_hash=${PREVIOUS_GIT_HASH} --key-file /tmp/deploy_rsa .travisci/deploy.yml
after_success:
    - echo "========== End after success script"

branches:
  only:
    - alpha
    - cicd
    
addons:
  ssh_known_hosts: ${SSH_HOST}
